##____________________ PiHole 2 [NETWORK/recursive-dnsserver]
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: always
    mac_address: d0:ca:ab:cd:ef:01
    cap_add:
      - NET_ADMIN
    networks:
      DNS-network:
        ipv4_address: 192.168.88.99
    environment:
      ServerIP: 192.168.88.99
      WEBPASSWORD: $PW_INT
      PHP_ENV_CONFIG: "/etc/lighttpd/conf-enabled/15-fastcgi-php.conf"
      TZ: $TZ
      DNS1: 192.168.88.89#53
      DNS2: 127.0.0.1
    volumes:
      - $USERDIR/docker/pihole/dnsmasq.d:/etc/dnsmasq.d:rw
      - $USERDIR/docker/pihole:/etc/pihole:rw
      - /etc/localtime:/etc/localtime:ro
      - $USERDIR/docker/pihole/var-log/pihole.log:/var/log/pihole.log
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
    dns:
      - 127.0.0.1
      - 192.168.88.89#53
# networks macvlan for pi-hole and unbound. Might be useful if you need them to have real LAN IPs. I don't need it anymore. 
networks:
  DNS-network:
    driver: macvlan
    driver_opts:
      parent: eno1
    ipam:
      config:
        - subnet: 192.168.88.0/24
          gateway: 192.168.88.1
          ip_range: 192.168.88.0/29
          aux_addresses:
            router: 192.168.88.1
            PiHole-1: 192.168.88.2
